# https://vektra.github.io/mockery/latest/configuration/
dir: "mocks/{{.PackageName}}"
with-expecter: True # https://vektra.github.io/mockery/v2.52/deprecations/#with-expecter
issue-845-fix: True # https://vektra.github.io/mockery/v2.50/deprecations/#issue-845-fix
resolve-type-alias: False # https://vektra.github.io/mockery/v2.50/deprecations/#resolve-type-alias
disable-version-string: True # https://vektra.github.io/mockery/v2.52/deprecations/#disable-version-string
packages:
  github.com/gkatanacio/go-serverless-template/pkg/greeting:
    config:
      all: True
      recursive: True
