version: "3"

services:
  golang:
    image: golang:1.14-stretch
    volumes:
      - .:/app:cached
    working_dir: /app
    env_file: .env
    environment:
      - GOPATH=/app/.go

  serverless:
    image: flemay/serverless
    volumes:
      - .:/app:cached
    working_dir: /app
    env_file: .env

  mockery:
    image: vektra/mockery
    volumes:
      - .:/app:cached
    working_dir: /app
