service: go-serverless-template

package:
  individually: true
  patterns:
    - '!./**'

provider:
  name: aws
  runtime: go1.x
  deploymentBucket:
    name: ${env:AWS_DEPLOYMENT_BUCKET}
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

functions:
  hello:
    handler: bin/hello
    package:
      patterns:
        - ./bin/hello
    timeout: 30
    memorySize: 128
    events:
      - schedule:
          rate: ${env:RUN_FREQUENCY}
    environment:
      HELLO_WHO: ${env:HELLO_WHO}
